# ==== Regen Development Run ====
# This is the regen development code for engine analyis. It will use chamber
# properties generated by the main code to evaluate regen circuit seperate
# from primary engine analysis. Eventaually, it will be integrated in the
# main code deck.

# ==== Solution Architecture ====
# 0 = Inlet, 1 = Outlet
# 1. Solve for initial guess at circuit P0 & dP (P1-P0) using known P1
# condition and assuming STP density
# 2. Solve for T1 using P0 guess, solve for actual P1
# 3. Guess new P0 based on previously calculated P1, repeat step 2 until
# results converge

import sys
import math
import numpy as np
import matplotlib.pyplot as plt
from rocketcea.cea_obj import CEA_Obj
import dataCollectionScript as dc

print(dc.engineProps)

np.set_printoptions(threshold=sys.maxsize)

# Gonna need to import dataCollectionScript and the relevant data it will produce.

# ==== Input Parameters ====
fuelStiffness = .20 # 20% injector stiffness
P_ce_req = (dc.P_inj/(1-fuelStiffness)) * dc.bar  # Required Coolant exit pressure, Pa
T_ci = 280.15 # Coolant Inlet Temperature, K

# ====DATA FORMAT:
# R, Z, pip, aeat, mach, cf, ivac, isp, p, t, rho, h, u, mw, cp, gam, son,
#   vis, cond, pran, condfz, pranfz
# channelFile = 'channelDesign_YJ1S-03.xlsx';
# channelProfile = channelProfileGen(channelFile);
# %channelProfile Layout
# % R, Z, R_floor, R_ceil, numChannels, channelWidth, finWidth, channelDepth,
# %channelCSA, channelPerim, channelAR
# [numRows, numCols] = size(engineProps);
# channelCSA = channelProfile(:,9);
# numChannels = channelProfile(:,5);
# channelPerim = channelProfile(:,10);
# mDot_chan = mDot_f./numChannels;
# Z = channelProfile(:,2);
# R_floor = channelProfile(:,3);
# R_ceil = channelProfile(:,4);
