# ==== Regen Development Run ====
# This is the regen development code for engine analyis. It uses chamber
# properties generated by the engine designer code to evaluate regen circuit seperate
# from primary engine analysis.

# ==== Architecture ====
# 1. User selects initial gas side wall temp, min fin width, and desired coolant outlet temp
# 2. At throat, exit, and injector plane solve for coolant convection coefficient
#    a. Solve with heat transfer equilibrium through wall
# 3. Using this convection coefficient, solve for the channel width needed
# 4. Stitch together geometry to generate full contour
# 5. Simulate full contour and determine outlet temp
#    a. Solve for coolant convection coefficient
#    b. Pick gas side wall temp and converge on equilibrium
#    c. Solve for temperature increase
#    d. Solve for pressure loss
# 6. If outlet temp is too high, increase gas side wall temp and repeat steps 2-5
# 7. Calculate strain and get conservative estimate for cycle life

import sys
import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from engine_designer.dataCollectionScript import Engine
from .bartzCorrelation import Bartz
from .jetAProps import getProps
from .pressureDrop import pressureDrop
from .strain import get_strain

np.set_printoptions(threshold=sys.maxsize) # Print full arrays (for debugging)

class regenJacket:
    # Initialize the jacket object upon declaration
    def __init__(self, engine, channel_h=0.002, wall_t=0.001, min_fin_w = 0.001, min_channel_w = 0.0015875, T_wg=750, T_co=462):
        self.engine = engine # Engine object to be jacketed
        self.channel_h = channel_h # Channel height (m)
        self.wall_t = wall_t # Inner wall thickness (m)
        self.min_fin_w = min_fin_w # Minimum manufacutrable fin width (m)
        self.min_channel_w = min_channel_w # Minimum manufacutrable channel width (m)
        self.T_wg = T_wg # Gas-side wall temperature initial estimate (K)
        self.T_co = T_co # Desired coolant outlet temperature (K)
        self.T_max = 900 # Max allowed temp for material (copper melts at 1358 K)

    def get_geometry(self):

        # ==== Define properties ====
        mDot = self.engine.mDot_f # Mass flow of coolant (kg/s)
        cond_w = 330 # W/m-k, copper conductivity
        T_ci = 280.15 # Coolant inlet temperature (K)
        cu_density = 8940 # Copper density (kg/m^3)

        # ==== Define Critical Points ====
        numPTS = np.size(self.engine.engineProps,0) # Number of engine stations
        i_inj = 0 # Injector face
        i_t = self.engine.throatInd + len(self.engine.chBarrel) # Throat
        i_exit = numPTS - 1 # Last point (-1 since this is zero indexed)
        criticals = [i_exit, i_t, i_inj]
        names = ["Exit", "Throat", "Injector face"] # For plotting

        def get_coolant_temps():
            # Determine reasonable estimates for coolant bulk temperatures at key stations
            # for use in heat transfer calculations
            T_co = self.T_co # Coolant outlet temp (K)
            critical_values = [] # Place to store values

            # Get coolant temps at critical points (assume linear increase)
            for i in criticals:
                temp = ((numPTS - i) / numPTS) * (T_co - T_ci) + T_ci
                R = self.engine.engineProps[i, 0] # Station inner radius
                critical_values.append([i, R, temp]) # Add the average station temp to the list
            return critical_values

        def get_critical_dimensions(ind, num_channels='1'):
        # Steps 2 & 3. Get the coolant convection coefficient and solve for channel width
            i = critical_values[ind][0]
            T_wg = self.T_wg # Initialize gas side wall temp to desired temp
            T_cb = critical_values[ind][2] # Coolant bulk temp
            R = critical_values[ind][1] # Station radius
            channel_w = self.min_channel_w # Inital channel width guess
            (rho_c, C_pc, cond_c, viscK_c) = getProps(T_cb) # Get coolant fluid properties
            q_in = 1 # bs initlialization
            q_out = 2 # bs initlialization
            # Converge on channel width and gas side wall temp
            while abs((q_in-q_out)/q_in) > 0.005:
                (h_g, qdot_ge, T_aw) = Bartz(self.engine, T_wg, i)
                T_wc = T_wg - qdot_ge*self.wall_t/cond_w # Solve for coolant side wall temp

                # Channel number is determined at the throat run. Other stations will use this value as a constant
                if ind == 1:
                    num_channels = math.floor(2*math.pi*(critical_values[ind][1]+self.wall_t) / (self.min_fin_w + channel_w))
                mDot_chan = mDot/num_channels

                D_hyd = 2 * channel_w * self.channel_h / (channel_w + self.channel_h) # Channel hydraulic diameter
                A_cc = channel_w * self.channel_h # Cross sectional area of channel (m^2)
                vel_c = mDot_chan/(A_cc * rho_c) # Coolant velocity in channel (m/s)
                Re_c = (vel_c * D_hyd) / viscK_c # Coolant Reynolds number
                Pr_c = viscK_c * rho_c * C_pc / cond_c # Coolant Prandtl Number
                h_c = 0.021 * (Re_c)**0.8 * (Pr_c)**0.4 * (0.64 + 0.36 * (T_cb/T_wc)) * (cond_c/D_hyd)

                length = 0.001 # Really doesn't impact anything but used in fin calcs. Could be set to anything
                perim_conf = 2 * length # Contact perimeter for fin efficiency calcs
                A_conf = length * self.min_fin_w # Contact area for fin efficiency calcs
                A_fin = 2 * self.channel_h * length # Area of single fin in analysis segment
                A_finTot = num_channels * A_fin # Total fin area
                A_totc = A_finTot + num_channels * channel_w * length # Total coolant side heat transfer area
                A_totg = 2 * math.pi * R * length #total hot gas side wall area

                #Run fin efficiency calculations to find the effective contact area
                m = math.sqrt((h_c * perim_conf)/(cond_w * A_conf)) # Fin efficiency parameter
                eta_fin = math.tanh(m * self.channel_h)/(m * self.channel_h) # Fin efficiency
                eta_tot = 1 - (((num_channels * A_fin)/A_totc) * (1 - eta_fin)) # Overall coolant side heat transfer efficiency

                q_in = qdot_ge * A_totg # Total heat entering wall from gasses (not the rate)
                q_out = h_c * A_totc * eta_tot * (T_wc - T_cb)
                # print(q_in, q_out, h_c, T_wg)

                # If too much heat is entering
                if q_in > q_out:
                    # Try lowering channel width if manufacturable
                    if channel_w > self.min_channel_w:
                        channel_w = channel_w - 0.001 * (channel_w - self.min_channel_w)
                    # Otherwise the only option is to increase wall temp
                    else:
                        T_wg = T_wg * 1.001
                else:
                    max_channel_w = (2*math.pi*(critical_values[ind][1]+self.wall_t) - self.min_fin_w * num_channels)/num_channels
                    # Increase channel width if possible
                    if channel_w < max_channel_w:
                        channel_w = channel_w * 1.001 # Increase channel width
                    # Otherwise gas side temp can be decreased
                    else:
                        T_wg = T_wg * .999
            fin_w = (2*math.pi*(critical_values[ind][1]+self.wall_t) - channel_w * num_channels)/num_channels
            critical_values[ind].append(channel_w)
            critical_values[ind].append(fin_w)
            return num_channels

        def get_all_dimensions():
            # Construct geometry for remaining stations
            profile = np.zeros([numPTS, 3]) # 200x3 array
            profile[:,0] = self.engine.engineProps[:,0] # Input radii as first col
            barrel_end = len(self.engine.chBarrel) # Index where constant raidus ends
            for i in range(np.size(profile, 0)):
                # In barrel
                if i <= barrel_end:
                    profile[i,1] = critical_values[2][3] # Assign channel width
                    profile[i,2] = critical_values[2][4] # Assign fin width
                # Converging section
                elif i < barrel_end + self.engine.throatInd:
                    delta_w = critical_values[2][3] - critical_values[1][3]
                    channel_w = profile[i,1] = critical_values[2][3] - (delta_w) * (i-barrel_end)/self.engine.throatInd
                    fin_w = 2 * math.pi * (self.engine.engineProps[i,0] + self.wall_t) / num_channels - channel_w
                    profile[i,1] = channel_w
                    profile[i,2] = fin_w
                # Diverging section
                else:
                    delta_w = critical_values[1][3] - critical_values[0][3]
                    channel_w = profile[i,1] = critical_values[1][3] - (delta_w) * (i-(barrel_end + self.engine.throatInd))/(numPTS - barrel_end - self.engine.throatInd)
                    fin_w = 2 * math.pi * (self.engine.engineProps[i,0] + self.wall_t) / num_channels - channel_w
                    profile[i,1] = channel_w
                    profile[i,2] = fin_w
            return profile

        def full_sim(num_channels):
            # Run full simulation of generated geometry to get coolant temp increase and pressure loss
            T_cb = T_ci # Initial bulk temp (K)
            P_c = self.engine.P_inj * 1.2 # Initial coolant pressure (bar) 1.2 included as stiffness
            wall_temps = np.zeros([numPTS,1])
            volume = 0 # To calculate mass of jacket (m^3) (may be used for future optimization)
            for x in range(numPTS):
                i = numPTS - x - 1 # Reverse order
                # Initialize parameters
                (rho_c, C_pc, cond_c, viscK_c) = getProps(T_cb) # Get coolant fluid properties
                channel_w = profile[i,1]
                fin_w = profile[i,2]
                R = profile[i,0]
                mDot_chan = mDot/num_channels

                q_in = 1 # bs initlialization
                q_out = 2 # bs initlialization
                T_wg = self.T_wg # Initialize gas side wall temp to desired temp
                # Converge on channel width and gas side wall temp
                while abs((q_in-q_out)/q_in) > 0.001:
                    (h_g, qdot_ge, T_aw) = Bartz(self.engine, T_wg, i)
                    T_wc = T_wg - qdot_ge*self.wall_t/cond_w # Solve for coolant side wall temp
                    D_hyd = 2 * channel_w * self.channel_h / (channel_w + self.channel_h) # Channel hydraulic diameter
                    A_cc = channel_w * self.channel_h # Cross sectional area of channel (m^2)
                    vel_c = mDot_chan/(A_cc * rho_c) # Coolant velocity in channel (m/s)
                    Re_c = (vel_c * D_hyd) / viscK_c # Coolant Reynolds number
                    Pr_c = viscK_c * rho_c * C_pc / cond_c # Coolant Prandtl Number
                    h_c = 0.021 * (Re_c)**0.8 * (Pr_c)**0.4 * (0.64 + 0.36 * (T_cb/T_wc)) * (cond_c/D_hyd)

                    if i > 0:
                        length = self.engine.engineProps[i,1] - self.engine.engineProps[i-1,1] # Height between stations
                        length = math.sqrt(length**2 + (R - profile[i-1,0])**2) # Account for angle at station
                    perim_conf = 2 * length # Contact perimeter for fin efficiency calcs
                    A_conf = length * self.min_fin_w # Contact area for fin efficiency calcs
                    A_fin = 2 * self.channel_h * length # Area of single fin in analysis segment
                    A_finTot = num_channels * A_fin # Total fin area
                    A_totc = A_finTot + num_channels * channel_w * length # Total coolant side heat transfer area
                    A_totg = 2 * math.pi * R * length #total hot gas side wall area

                    #Run fin efficiency calculations to find the effective contact area
                    m = math.sqrt((h_c * perim_conf)/(cond_w * A_conf)) # Fin efficiency parameter
                    eta_fin = math.tanh(m * self.channel_h)/(m * self.channel_h) # Fin efficiency
                    eta_tot = 1 - (((num_channels * A_fin)/A_totc) * (1 - eta_fin)) # Overall coolant side heat transfer efficiency

                    q_out = h_c * (T_wc - T_cb) * A_totc * eta_tot # Total heat transfer = flux * effective area
                    q_in = qdot_ge * A_totg

                    # print(T_wg, q_in, q_out)
                    # If too much heat is entering
                    if q_in > q_out:
                        T_wg = T_wg * (1+0.1*abs((q_in-q_out)/(q_in+q_out)))
                    # If too little is entering
                    else:
                        T_wg = T_wg * (1-0.1*abs((q_in-q_out)/(q_in+q_out)))

                dT_c = ((q_in + q_out)/2)/(C_pc * mDot) # Temperature change in coolant
                T_cb += dT_c
                wall_temps[i,0] = T_wg
                strain = get_strain(R, self.wall_t, (T_wg+T_wc)/2, T_wg-T_wc, channel_w) # Should be pretty low
                dP = pressureDrop(A_cc, D_hyd, mDot_chan, rho_c, length, viscK_c)
                P_c += dP/100000
                volume += (2*math.pi*R * self.wall_t + fin_w * self.channel_h * num_channels) * length
                # print(T_wg, qdot_ge, T_cb, channel_w)
            mass = volume * cu_density
            return (T_cb, P_c, wall_temps, mass)

        def outer_jacket(engine):
            # Estimate mass of steel shell surroudning engine
            st_density = 8050 # Density of steel (kg/m^3)
            thickness = 0.005 # Thickenss of outer jacket (m)
            R = engine.engineProps[0,0] + thickness/2 # Outer jacket radius (m)
            length = engine.engineProps[199,1] # Jacket length (m)
            vol = 2*math.pi*R * thickness * length # Outer jacket volume (m^3)
            mass = vol * st_density
            return mass

        # Main loop
        while True:
            critical_values = get_coolant_temps()
            num_channels = get_critical_dimensions(1)
            get_critical_dimensions(0, num_channels) # Exit
            get_critical_dimensions(2, num_channels) # Barrel
            # print(critical_values)
            profile = get_all_dimensions()
            (T_co, P_c, wall_temps, inner_mass) = full_sim(num_channels)
            # print(T_co, self.T_wg)
            # Increase wall gas temp if coolant outlet is too hot
            if T_co > self.T_co and self.T_wg < self.T_max:
                self.T_wg = self.T_wg * 1.05
                # Stop at max acceptable gas wall temp
                if self.T_wg > self.T_max:
                    self.T_wg = self.T_max
                    print("Max wall temps reached. Coolant outlet temp cannot be further minimized.")
            else:
                break
            # print("Iteration complete")
        print("-<=Analysis Complete=>-\nCoolant Outlet Temp (K): " + str(T_co) + "\nRequired Coolant Inlet Pressure (bar): " + str(P_c))
        outer_mass = outer_jacket(self.engine)
        mass = inner_mass + outer_mass
        print("Inner Jacket Mass (kg): " + str(inner_mass))
        print("Outer Jacket Mass (kg): " + str(outer_mass))
        print("Total Mass (kg): " + str(mass))

        # USEFUL PLOTS:
        # Channel Width
        # plt.plot(profile[:,1])
        # plt.xlabel('Distance from Injector', fontsize=16)
        # plt.ylabel('Channel Width', fontsize=16)
        # Wall Temp
        plt.plot(self.engine.engineProps[:,1], wall_temps)
        plt.xlabel('Distance from Injector (m)', fontsize=16)
        plt.ylabel('Wall Temperature (K)', fontsize=16)
        plt.show()

        return (profile, T_co, mass)
