# ==== Regen Development Run ====
# This is the regen development code for engine analyis. It will use chamber
# properties generated by the main code to evaluate regen circuit seperate
# from primary engine analysis. Eventaually, it will be integrated in the
# main code deck.

# ==== Solution Architecture (Will need tweaking) ====
# 1. Create the contour and property array for all 200 points of the nozzle
# 2. Pick four points to test with: Injector face, converging section, throat,
# nozzle exit. We’ll call these the “critical stations”
# 3. Define wall thickness = 1 mm and height = 1 mm
# 4. Define range of fin thicknesses and range of channel thicknesses for testing
# 5. Iterate through stations to find total heat flux and thus coolant temperature
# deltas at each station. Use this to get the bulk temperatures at each critical station
# 6. For each critical station:
#     a. For each combination of fin and channel widths:
#          i. Solve thermal equilibrium (Qin = Qout)
#          ii. Calculate inner and outer wall temperatures
#          iii. Run stress.py with the given average wall temperature and delta
#          iv. Save FOS’s to an array
# 7. Plot the FOS against channel and fin widths

import sys
import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from engine_designer.dataCollectionScript import Engine
from .bartzCorrelation import Bartz
from .jetAProps import getProps
from .pressureDrop import pressureDrop
from .stress import get_fos
from .stress_v2 import get_fos_2

np.set_printoptions(threshold=sys.maxsize) # Print full arrays for debugging

class regenJacket:
    # Initialize the jacket object upon declaration
    def __init__(self, engine, channel_h=0.001, wall_t=0.001, min_fos=1.2, min_fin_w = 0.001, min_channel_w = 0.0015875/2, T_wg=700):
        self.engine = engine # Engine object to be jacketed
        self.channel_h = channel_h # Channel height (m)
        self.wall_t = wall_t # Inner wall thickness (m)
        self.min_fos = min_fos # Minimum factor of safety
        self.min_fin_w = min_fin_w # Minimum manufacutrable fin width (m)
        self.min_channel_w = min_channel_w # Minimum manufacutrable channel width (m)
        self.T_wg = T_wg # Gas-side wall temperature initial estimate (K)

    # Solve for channel contour
    def get_geometry(self):

        # ==== Define properties ====
        mDot = self.engine.mDot_f # Mass flow of coolant (kg/s)
        cond_w = 330 # W/m-k, copper conductivity

        # ==== Find Critical Points ====
        i_inj = 0 # injector face
        i_t = self.engine.throatInd + 100 # throat
        i_exit = 199 # Last point
        criticals = [i_exit, i_t, i_inj]
        names = ["Exit", "Throat", "Injector face"] # For plotting

        def temp_sim():
            # ==== Temperature calculations ====
            T_ci = 280.15 # Coolant inlet temperature (K)
            T_cb = T_ci # Set coolant bulk temperature (K)
            critical_values = []

            # Loop through stations (from exit to inj) to find coolant temperatures at critical points
            for i in range(self.engine.engineProps.shape[0] - 1, -1, -1):
                (rho_c, C_pc, cond_c, viscK_c) = getProps(T_cb)
                if i > 0:
                    length = self.engine.engineProps[i, 1] - self.engine.engineProps[i - 1, 1] #Station "thickness"
                R = self.engine.engineProps[i, 0] # Station inner radius
                A_totg = 2 * math.pi * R * length # Total hot gas side wall area for heat transfer
                (h_g, qdot_ge, T_aw) = Bartz(self.engine, self.T_wg, i)
                q_ge = qdot_ge * A_totg # Total heat transfer from gas side (W/m^2 * m^2 = W)
                dT_c = (q_ge)/(C_pc * mDot) # Temperature change in coolant
                if i in criticals:
                    critical_values.append([i, R, (2*T_cb + dT_c)/2]) # Add the average station temp to the list
                T_cb += dT_c
            return critical_values

        # chw_range = [0.0005, 0.001, 0.0015, 0.002, 0.0025, 0.003, 0.0035, 0.004, 0.0045, 0.005] # List of channel widths to test (m)
        # fw_range = [0.0005, 0.001, 0.0015, 0.002, 0.0025, 0.003, 0.0035, 0.004, 0.0045, 0.005] # List of fin widths to test (m)

        def critical_fos(i, channel_w, fin_w):

            R = critical_values[i][1]
            T_cb = critical_values[i][2]
            (rho_c, C_pc, cond_c, viscK_c) = getProps(T_cb) # Update fluid properties
            length = 0.001 # Really doesn't impact anything but used in fin calcs. Could be set to anything
            # Simulate for each combination of fin and channel widths

            # Parameters
            D_hyd = 2 * channel_w * self.channel_h / (channel_w + self.channel_h) # Channel hydraulic diameter
            num_channels = 2 * math.pi * (R + self.wall_t) / (fin_w + channel_w) # Channel number
            mDot_chan = mDot / num_channels # Mass flow rate through each one (kg/s)
            A_cc = channel_w * self.channel_h # Cross sectional area of channel (m^2)
            vel_c = mDot_chan/(A_cc * rho_c) # Coolant velocity in channel (m/s)
            Re_c = (vel_c * D_hyd)/viscK_c # Coolant Reynolds number
            Pr_c = viscK_c * rho_c * C_pc / cond_c # Coolant Prandtl Number

            # Geometric Parameters (AT STATION, NOT SUM) !!! Double check these !!!
            L_cor = self.channel_h # Corrected channel height for fin efficiency calcs
            perim_conf = 2 * length # Contact perimeter for fin efficiency calcs
            A_conf = length * fin_w #contact area for fin efficiency calcs
            A_fin = 2 * L_cor * length # Area of single fin in analysis segment, corrected for adiabatic tip
            A_finTot = num_channels * A_fin # Total fin area
            A_totc = A_finTot + num_channels * channel_w * length # Total coolant side heat transfer area
            A_totg = 2 * math.pi * R * length #total hot gas side wall area for heat transfer

            # print(perim_conf/A_conf)
            # Converge on thermal equilibrium
            converged = False
            while not converged:
                (h_g, qdot_ge, T_aw) = Bartz(self.engine, self.T_wg, i)
                q_ge = qdot_ge * A_totg
                T_wc = self.T_wg - qdot_ge * self.wall_t / cond_w # Find cold side wall temp
                h_c = 0.021 * (Re_c)**0.8 * (Pr_c)**0.4 * (0.64 + 0.36 * (T_cb/T_wc)) * (cond_c/D_hyd)
                #Run fin efficiency calculations to find the effective contact area
                m = math.sqrt((h_c * perim_conf)/(cond_w * A_conf)) # Fin efficiency parameter
                eta_fin = math.tanh(m * L_cor)/(m * L_cor) # Fin efficiency
                eta_tot = 1 - (((num_channels * A_fin)/A_totc) * (1 - eta_fin)) # Overall coolant side heat transfer efficiency
                q_ce = h_c * (T_wc - T_cb) * A_totc * eta_tot # Total heat transfer = flux * effective area
                err = abs((q_ce-q_ge)/q_ge)
                # print(h_c * self.wall_t / cond_w)
                if err < 0.005:
                    converged = True
                else:
                    if q_ge > q_ce:
                        self.T_wg = self.T_wg + (10 * err) #Increase T_wg since coolant can't draw enough heat
                    elif q_ce > q_ge:
                        self.T_wg = self.T_wg - (10 * err) #Decrease T_wg since coolant can draw more heat
            biot = h_c * (fin_w/2) / cond_w
            # print(biot)
            meanT = (self.T_wg + T_wc) / 2 # Mean temp for stress calculations (K)
            dT = self.T_wg - T_wc # Temp difference for stress calculations (K)
            # (ny_conserv, ny_precise, nu_conserv, nu_precise) = get_fos(R, self.wall_t, meanT, dT)
            (ny_conserv, ny_precise, nu_conserv, nu_precise) = get_fos_2(R, self.wall_t, meanT, self.T_wg, dT)
            # print(T_cb)
            fos = nu_conserv

            return (fos, num_channels)

        def get_throat_dimensions():
            i = 1 # Throat index
            channel_w = self.min_channel_w
            fin_w = self.min_fin_w
            (fos, num_channels) = critical_fos(i, channel_w, fin_w) # Highest fos possible
            # If this is still too low, notify user and continue
            if fos < self.min_fos:
                print("Desired FOS cannot be reached. Proceeding with maximum possible: " + str(fos))
            # Otherwise we can increase channel size proportional to this difference
            else:
                fos_delta = fos - self.min_fos # How much fos buffer we have
                while fos_delta > 0.001:
                    channel_w = channel_w * (0.3 * fos_delta + 1) # Increase channel width
                    # fin_w = fin_w * (fos_delta + 1) # Increase fin width (not recommended)
                    (fos, num_channels) = critical_fos(i, channel_w, fin_w) # Recalculate FOS
                    fos_delta = fos - self.min_fos # How much fos buffer we have
                    # Make sure fin width doesn't get too small
                    if fin_w <= self.min_fin_w:
                        fin_w = self.min_fin_w
                        channel_w = 2 * math.pi * (critical_values[i][1] + self.wall_t) / num_channels - fin_w
                        break
            # Round channel number to integer and accomidate with fin width
            circum = 2 * math.pi * (critical_values[i][1] + self.wall_t)
            num_channels = round(num_channels)
            fin_w = (circum - num_channels * channel_w) / num_channels
            critical_values[i].append(channel_w)
            critical_values[i].append(fin_w)
            critical_values[i].append(fos)
            print(channel_w, fin_w, fos)
            return num_channels

        def get_critical_dimensions(i, num_channels):
            # Calculate dimensions for critical stations other than throat (barrel and exit)
            channel_w = self.min_channel_w # Set initial channel width to optimal value
            fin_w = (2 * math.pi * (critical_values[i][1] + self.wall_t) - (num_channels * channel_w))/num_channels # Solve for fin width given channel number and channel width
            (fos, num_channels) = critical_fos(i, channel_w, fin_w) # Find FOS with this duo
            w_sum = channel_w + fin_w # Sum of widths. Must remian constant
            # If FOS is still too low, notify user and continue
            if fos < self.min_fos:
                print("Desired FOS cannot be reached. Proceeding with maximum possible: " + str(fos))
            # Otherwise we can increase the fin and channel sizes proportional to this difference
            else:
                fos_delta = fos - self.min_fos # How much fos buffer we have
                while fos_delta > 0.001:
                    channel_w = channel_w * (0.1 * fos_delta + 1) # Increase channel width
                    fin_w = w_sum - channel_w # Get fin width
                    (fos, num_channels) = critical_fos(i, channel_w, fin_w) # Recalculate FOS
                    fos_delta = fos - self.min_fos # How much fos buffer we have
                    # Make sure fin width doesn't get too small
                    if fin_w <= self.min_fin_w:
                        fin_w = self.min_fin_w
                        channel_w = w_sum - fin_w
                        break
            critical_values[i].append(channel_w)
            critical_values[i].append(fin_w)
            critical_values[i].append(fos)
            print(channel_w, fin_w, fos)

        def get_all_dimensions():

            # Construct geometry for remaining stations
            profile = np.zeros([np.size(self.engine.engineProps, 0), 3])
            profile[:,0] = self.engine.engineProps[:,0]
            barrel_end = len(self.engine.chBarrel) # Index where constant raidus ends
            for i in range(np.size(profile, 0)):
                # In barrel
                if i <= barrel_end:
                    profile[i,1] = critical_values[2][3] # Assign channel width
                    profile[i,2] = critical_values[2][4] # Assign fin width
                # Converging section
                elif i < barrel_end + self.engine.throatInd:
                    delta_w = critical_values[2][3] - critical_values[1][3]
                    channel_w = profile[i,1] = critical_values[2][3] - (delta_w) * (i-100)/self.engine.throatInd
                    fin_w = 2 * math.pi * (self.engine.engineProps[i,0] + self.wall_t) / num_channels - channel_w
                    profile[i,1] = channel_w
                    profile[i,2] = fin_w
                # Diverging section
                else:
                    delta_w = critical_values[1][3] - critical_values[0][3]
                    channel_w = profile[i,1] = critical_values[1][3] - (delta_w) * (i-(100 + self.engine.throatInd))/(self.engine.throatInd + 100)
                    fin_w = 2 * math.pi * (self.engine.engineProps[i,0] + self.wall_t) / num_channels - channel_w
                    profile[i,1] = channel_w
                    profile[i,2] = fin_w
            return profile

        critical_values = temp_sim() # Solve for cirical station coolant temperatures
        # print(critical_values)
        num_channels = get_throat_dimensions()
        get_critical_dimensions(0, num_channels) # barrel
        get_critical_dimensions(2, num_channels) # exit
        profile = get_all_dimensions()

        print(profile)
        # print(self.engine.engineProps)
        plt.plot(profile[:,1])
        plt.xlabel('Distance from Injector', fontsize=16)
        plt.ylabel('Channel Width', fontsize=16)
        plt.ylim([0,0.002])
        plt.show()
