# ==== Regen Development Run ====
# This is the regen development code for engine analyis. It will use chamber
# properties generated by the main code to evaluate regen circuit seperate
# from primary engine analysis. Eventaually, it will be integrated in the
# main code deck.

# ==== Solution Architecture ====
# 0 = Inlet, 1 = Outlet
# 1. Solve for initial guess at circuit P0 & dP (P1-P0) using known P1
# condition and assuming STP density
# 2. Solve for T1 using P0 guess, solve for actual P1
# 3. Guess new P0 based on previously calculated P1, repeat step 2 until
# results converge

import sys
import math
import numpy as np
import matplotlib.pyplot as plt
import dataCollectionScript as dc
from bartzCorrelation import Bartz
from jetAProps import getProps
from pressureDrop import pressureDrop

np.set_printoptions(threshold=sys.maxsize)

# ==== Input Parameters ====
fuelStiffness = .20 # 20% injector stiffness
P_ce_req = (dc.P_inj/(1-fuelStiffness)) * dc.bar  # Required Coolant exit pressure, Pa
P_in = P_ce_req # Required inlet pressure (Pa) Initialize as outlet pressure
T_ci = 280.15 # Coolant Inlet Temperature, K
T_co = 500 # Coolant Outlet Tempertaure, K
T_wg = 800 # Design wall temperature, K

# Design Specs
numChannels = 50
Ch_fin_rat = .5 # Higher values have less pressure drop but are worse at cooling

# Run Bartz Correlation to find gas side convection coefficient
# DUE TO BARTZ CORRELATION BEING DEVELOPED IN ENGLISH UNITS, VALUES
# CONVERTED TO ENGLISH UNITS IN EQUATIONS BELOW THEN RECONVERTED
g = 32.174 # Gravity, ft/s^2
T_wg = T_wg * 1.8 # Convert K to R
C_star = dc.C_star * 3.28084 # Convert m/s to ft/s
R_tCurve = dc.R_tCurve * 39.3701 # Convert m to in
R_t = dc.R_t * 39.3701 # Convert m to in
P_c = dc.P_inj_psi # Injector face pressure in psi
T_c0 = dc.engineProps[0,9] * 1.8 # Convert K to R
gam0 = dc.engineProps[0,15] # Chamber stagnation gamma
    # !!! LOOK INTO THIS. cp_ns probably needs a more general assignment
    # Old cp_ns - new estimate used as 2.2 KJ/Kg*K - correlation to come later
    # NOTE: Effective specific heat used (instead of Frozen)
    # cp_ns = engineProps(1,15).*0.23884; %Convert from Joules to BTU/lb*F
cp_ns = 2.2 * 0.23884 # Convert from Kilo-Joules to BTU/lb*F
    # Originally used effective prandtl number from CEA, switched to gamma
    # correlation
# praneff_ns2 = dc.engineProps[0,21] # No conversion needed
praneff_ns = (4*gam0)/(9*gam0-5)
visc_ns = (dc.engineProps[0,17]/1000) * (0.0672/12) # Convert to Poise then to lb/in-s

# Package info to make calling Bartz cleaner
bartzData = [T_wg, T_c0, R_t, P_c, C_star, R_tCurve, praneff_ns, visc_ns, cp_ns, g]

mDot_chan = dc.mDot_f / numChannels
T_cb = T_ci #Set coolant bulk temp to inlet temp

# Material Parameters & Constants
cond_w = 330 # W/m-k, wall conductivity
E = 115 * (10**9) # Young's modulus of copper, Pa (this can vary with T, so more work is needed here)
a = 17 * (10**-6) # Thermal expansion coefficient, K^-1
v = 0.35 # Poisson's ratio
yield_str = 70 * (1000000) # Max stress before yield (Pa)
ultimate_str = 220 * (1000000) # Max stress before fracture (Pa)
design_stress = 100 * (1000000)

# temps = np.array([])

# Solve for the channel height and inner wall thickness at all stations:
# Loop through stations:
for i in range(dc.engineProps.shape[0]-1):
    (h_g, qdot_ge, T_aw) = Bartz(dc.engineProps, bartzData, i)

    len = dc.engineProps[i + 1, 1] - dc.engineProps[i, 1]
    R = dc.engineProps[i, 0] # Station cross section radius
    Ch_w = 2 * math.pi * R * Ch_fin_rat / numChannels # Solve for width of channel
    Ch_h = Ch_w # Starting geometry is square. Convergence will happen to get ideal value
    t_fin = Ch_w * (1 - Ch_fin_rat) / Ch_fin_rat # Fin width
    A_cc = Ch_w * Ch_h # Cross sectional area of channel
    D_hyd = (2 * A_cc)/(Ch_w + Ch_h) # Channel Hydraulic diameter (m)

    (rho_c, C_pc, cond_c, viscK_c) = getProps(T_cb)

    vel_c = mDot_chan/(A_cc * rho_c) # Coolant velocity in channel (m/s)

    t_stay = len / vel_c # Coolant stay time in channel segment (s)

    Re_c = (vel_c * D_hyd)/viscK_c # Coolant Reynolds number
    Pr_c = viscK_c * rho_c * C_pc / cond_c # Coolant Prandtl Number
    # Run convergence to find wall_t:
    wall_t = 0.001 #M

    T_wc = T_wg/1.8 - qdot_ge * wall_t / cond_w

    # Figure out the channel height
    # Properties independent of channel height:
    A_totg = 2 * math.pi * R * len # Total hot gas side wall area for heat transfer
    A_conf = len * t_fin # Contact area for fin efficiency calcs
    q_ge = qdot_ge * A_totg # Total heat transfer from gas side (W/m^2 * m^2 = W)
    h_c = qdot_ge/(T_wc - T_cb) # Initial ballpark guess for coolant side convection coefficient
    h_c_old = 0 # Initalize variable

    # Converge on channel height. This happens pretty fast (typically only ~5 loops)
    while (abs(h_c_old - h_c)/h_c > 0.00001):
        h_c_old = h_c
        # Geometric Parameters (AT STATION, NOT SUM) !!! Double check these !!!
        L_cor = Ch_h + t_fin/2 # Corrected channel height for fin efficiency calcs
        perim_conf = 2 * len + 2 * t_fin # Contact perimeter for fin efficiency calcs
        A_fin = 2 * L_cor * len # Area of single fin in analysis segment, corrected for adiabatic tip
        A_finTot = numChannels * A_fin # Total fin area
        A_totc = A_finTot + numChannels * Ch_w * len # Total coolant side heat transfer area

        #Run fin efficiency calculations to find the effective contact area
        m = math.sqrt((h_c * perim_conf)/(cond_w * A_conf)) # Fin efficiency parameter
        eta_fin = math.tanh(m * L_cor)/(m * L_cor) # Fin efficiency
        eta_tot = 1 - (((numChannels * A_fin)/A_totc) * (1 - eta_fin)) # Overall coolant side heat transfer efficiency
        qdot_ce = q_ge / (A_totc * eta_tot) # Coolant side heat flux (gas side heat rate divided by effective area)
        h_c = qdot_ce/(T_wc - T_cb) # Calculate coolant convection coefficient

        # Calculate the new hydraulic diameter with this coefficient
        D_hyd_1 = 0.021 * ((4 * mDot_chan/(viscK_c * math.pi))**0.8) * (Pr_c**0.4) # D_hyd_1 included for readability
        D_hyd = (D_hyd_1 * (0.64 + 0.36 * (T_cb/T_wc)) * (cond_c/h_c)) ** (1/1.8)
        Ch_h = (D_hyd * Ch_w)/(2*Ch_w + D_hyd) # Highest channel height allowed

    q_ce = h_c * (T_wc - T_cb) * A_totc * eta_tot # Total heat transfer = flux * effective area
    dT_c = ((q_ce + q_ge)/2)/(C_pc * mDot_chan * numChannels) # Temperature change in coolant
    T_cb += dT_c
    # temps = np.append(temps, T_cb)
    # print(Ch_h, Ch_w, Ch_h/Ch_w, D_hyd, dT_c, h_c)

    # Figure out pressure loss
    channelCSA = Ch_w * Ch_h # Cross sectional area of each channel
    channelPerim = 2 * Ch_w + 2 * Ch_h # Perimeter of each channel
    dP = pressureDrop(channelCSA, channelPerim, mDot_chan, rho_c, len, viscK_c)
    P_in += dP
    print(T_cb)


print(P_ce_req)
print(P_in / dc.bar)

# plt.plot(temps)
# plt.show()
